<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\TTwen.Domain\TTwen.Domain.csproj" />
    <ProjectReference Include="..\..\src\TTwen.Application\TTwen.Application.csproj" />
    <ProjectReference Include="..\..\src\TTwen.Simulator\TTwen.Simulator.csproj" />
  </ItemGroup>
</Project>